### ISSUE TITLE
running docker build - hangs on 'useradd' step - actually its the chown /opt/conda step

### ISSUE THREAD

**Issue by cicorias** [wballard/kerasvideo#2]
Not sure why but I've tried this on 2 different windows for docker latest images.  The step where useradd occurs, which chains to `chown /opt/conda -R...`  - that process eventually blocks and goes into an uninterruptable sleep state ` D`

The following I got by `docker exec` into the build container at this state to see it's state.
```
USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
root         1  0.0  0.0   4500    72 ?        Ss   05:32   0:00 /bin/sh -c useradd -m -s /bin/bash -N -u $NB_UID $NB_USER &&     mkdirroot        12  3.7  0.0  12960   852 ?        D    05:32   0:45 chown keras /opt/conda -R
root        13  0.0  0.0  18248  2832 pts/0    Ss   05:43   0:00 bash
root        99  0.0  0.0  34420  2820 pts/0    R+   05:52   0:00 ps aux
```

The step shown in the console from build is 
```
creating default environment...
using -f (force) option
installation finished.
Removing intermediate container fe2853a4e525
 ---> 2a5b9f8d3564
Step 8/14 : RUN useradd -m -s /bin/bash -N -u $NB_UID $NB_USER &&     mkdir -p $CONDA_DIR &&     chown keras $CONDA_DIR -R &&     mkdir -p /src &&     chown keras /src
 ---> Running in cdc73aad980d
```

Making it all run as root, removing the chown step, works fine

**Comment by wballard** [comment]
I merged up the 2018 branch — can you try again after a pull?

**Comment by cicorias** [comment]
I’ll try again. I’ll close now. If it fails again I’ll open again..  I did fork and fix, but no PR yet

**Comment by cicorias** [comment]
It was the chown that was hanging. I’ll try on my Mac too 
https://github.com/wballard/kerasvideo/blob/master/Dockerfile#L23
