### ISSUE TITLE
From your Pack book p21

### ISSUE THREAD

**Issue by rmiaouh** [wballard/kerasvideo#4]
Hi, i'm page 21 from your book (deep learning images with tensorflow)
I have a something wrong, i can't import keras in my IPYTHON. Why? Is the Ipython linked with the docker ?

**Comment by rmiaouh** [comment]
" ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-10-88d96843a926> in <module>
----> 1 import keras

ModuleNotFoundError: No module named 'keras' "

**Comment by wballard** [comment]
You running the notebook from the Docker container?
